### ISSUE TITLE
iRASPA thumbnail extension using excessive memory

### ISSUE THREAD

**Issue by ltalirz** [iRASPA/iRASPA-COCOA#2]
I just noticed this on an M1 Macbook air with MacOS 11.4

![Screen Shot 2021-06-07 at 09 27 35](https://user-images.githubusercontent.com/1053245/120993312-b10d1580-c783-11eb-839f-31a0f0fc647f.png)

Just reporting this here in case it helps - I don't know how to reproduce this

**Comment by dubbelda** [comment]
The thumbnail extension is called by the operating system to provide thumbnails for Finder (for pdf and cif-files). If you have many of these, it runs them in parallel and might use a lot of memory (for large pdb's). But this should be _temporary_.
Let me know if you have this issue for longer times.

**Comment by ltalirz** [comment]
I've had issues on the M1 where often when I reopened the machine it mentioned that the system was running out of memory.
I don't know whether it was related to this extension, it could well be something else.
I'll report if I encounter the issue again.

I still think that 2.5GB of memory for the thumbnail extension is quite a lot and may result in surprises for users, even if it just occurs occasionally.

**Comment by ltalirz** [comment]
![image](https://user-images.githubusercontent.com/1053245/121533168-4fa5aa80-ca00-11eb-8470-32acea206aeb.png)

**Comment by dubbelda** [comment]
Some tips I read is to relaunch the Finder (Force Quit -> Finder -> relaunch).

**Comment by ltalirz** [comment]
Is there a way to disable/unregister the iRASPA thumbnail extension?

**Comment by dubbelda** [comment]
I think in "System Preferences" -> "Extensions" you can disable extensions:
<img width="780" alt="Screen Shot 2021-06-14 at 09 23 58" src="https://user-images.githubusercontent.com/5294576/121854293-44999580-ccf2-11eb-84b1-d7464333e6c2.png">

**Comment by dubbelda** [comment]
A few points:
1) An extension is a small program (in this case using iRASPA to make a picture) called by macOS. MacOS determines how and when these extensions are called. For example, when you open Finder. It can open 1 or 5 or more as it sees fit.
2) System memory for M1 is different from Intel. It has been observed that many processes show up as using more memory. But, there is no need for the system to remove memory unless it is needed by another process. So, unless you notice significant slow-down it might be just a bookkeeping issue of memory of the M1.
3) One potential issue that might be caused by iRASPA is that you have pdb, cif, or xyz-files with a "wrong" format, it might lead iRASPA to think that there are extremely large amount of atoms in the file. This would lead to a crash or potentially to the process taking a ridiculous amount of time. I will change the limit of the thumbnails to files with less than 50,000 atoms.

**Comment by ltalirz** [comment]
Thanks for the info!

**Comment by dubbelda** [comment]
These for quicklook (for example using the spacebar when having the file selected in the Finder)
<img width="780" alt="Screen Shot 2021-06-14 at 09 36 01" src="https://user-images.githubusercontent.com/5294576/121855789-07ce9e00-ccf4-11eb-9a22-065371753a53.png">
